name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
  BRANCH_NAME: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}

jobs:
  deploy_pr:
    runs-on: ubuntu-latest
    name: Deploy PR on Nomad
    if: github.event_name == 'pull_request' && !github.event.pull_request.draft
    steps:
      - name: Wait for build, lint and test checks
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ env.COMMIT_SHA }}
          running-workflow-name: 'Deploy PR on Nomad'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Trigger Deploy PR
        run: |
          echo "deploying PR ${{ github.event.repository.name }} ${{ env.BRANCH_NAME }} ${{ env.COMMIT_SHA }}"
          curl --version
          curl --fail -o output -X PUT -H "Content-Type: text/plain" -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID}}" -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET}}" -H "X-Consul-Token: ${{ secrets.CONSUL_TOKEN }}" --data "${{ env.COMMIT_SHA }}" "https://api.r2unit.io/v1/deploy/${{ github.event.repository.name }}/${{ env.BRANCH_NAME }}"
          cat output

  deploy_branch:
    runs-on: ubuntu-latest
    name: Deploy Branch on Nomad
    if: github.event_name != 'pull_request'
    steps:
      - name: Wait for build, lint and test checks
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ env.COMMIT_SHA }}
          running-workflow-name: 'Deploy Branch on Nomad'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Trigger Deploy Branch
        run: |
          echo "deploying ${{ github.event.repository.name }} ${{ env.BRANCH_NAME }} ${{ env.COMMIT_SHA }}"
          curl --version
          curl --fail -o output -X PUT -H "Content-Type: text/plain" -H "CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID}}" -H "CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET}}" -H "X-Consul-Token: ${{ secrets.CONSUL_TOKEN }}" --data "${{ env.COMMIT_SHA }}" "https://api.r2unit.io/v1/deploy/${{ github.event.repository.name }}/${{ env.BRANCH_NAME }}"
          cat output
